//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerbrauchLib3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verbrauch
    {
        public int Id { get; set; }
        public string Wasser { get; set; }
        public string Strom { get; set; }
        public string Warmwasser { get; set; }
        public string Wärme { get; set; }
        public string Monat { get; set; }
        public string Jahr { get; set; }
        public int WohnungId { get; set; }
    
        public virtual Wohnung Wohnung { get; set; }
    }
}
